.TH "defendguin" "6" "0.0.13 - 2020.05.23" "Bill Kendrick" "Games"
.SH "NAME"
.LP 
defendguin \- A bidirectionally scrolling space game based on Defender.
.SH "SYNTAX"
.LP 
defendguin [\fIoptions\fP]
.SH "DESCRIPTION"
.LP 
Aliens are attacking earth, kidnapping little penguinoids and converting
them into mutants.  Helping them on their way are some other nasty alien
ships, of which there are plenty.  Defeat them and save the penguinoids.
.SH "OPTIONS"
.LP 
.TP 
\fB\-\-disable-sound\fR
Disables sound and music.
.TP
\fB\-\-fullscreen\fR
Runs in fullscreen mode, if possible.
.TP 
\fB\-\-help\fR
Output help information and exit.
.TP 
\fB\-\-version\fR
Output version information and exit.
.TP
\fB\-\-usage\fR
Displays acceptable command\-line options.
.SH "FILES"
\fI/usr/local/share/defendguin/\fP \- Sound, music and graphics data.
.LP 
.SH "AUTHORS"
.LP 
Bill Kendrick <bill@newbreedsoftware.com> \- Programming and graphics.
.br
Sami I Saarnio <saarnio@cc.helsinki.fi> \- Music
.br
Niko Nyman \- Music
.LP
See "AUTHORS.txt" and "CHANGES.txt" for full credits.
